language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit -v --coverage-text
